name: Android CI
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Android Build
        uses: vgaidarji/android-github-actions-build@v1.0.1
